apiVersion: v2
name: nautikalpanel
description: Helm chart for Nautikalpanel - A game server orchestration platform for Kubernetes
type: application
version: 0.1.01
appVersion: "0.1.0"
keywords:
  - game-server
  - orchestration
  - kubernetes
home: https://andyslucky.github.io/nautikalpanel/